spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coffeetaste
      username: coffeetaste
      password: coffeetastepass
      authentication-database: coffeetaste

server:
  port: 8008
